package daos;

public enum Corral {
    HEAD_COUNT,
    DAY,
    INITIAL_WEIGHT,
    TEMPERATURE,
    PORCENTAGE_WEIGHT_MATERIA_SECA,
    ACTUAL_WEIGHT,
    FOOD_SILO_SORGO,
    FOOD_MAIZ,
    FOOD_EXPELLER_SOJA,
    FOOD_PREMEZCLA_MINERAL,
    FOOD_MATERIA_SECA,
    FACTOR_MATERIA_SECA
}
