package daos;

public enum Corral {
    CABEZAS,
    DIA,
    PESO_INICIAL,
    TEMPERATURA,
    PORCENTAJE_PESO_MATERIA_SECA,
    PESO_ACTUAL,
    ALIMENTO_SILO_SORGO,
    ALIMENTO_MAIZ,
    ALIMENTO_EXPELLER_SOJA,
    ALIMENTO_PREMEZCLA_MINERAL,
    ALIMENTO_MATERIA_SECA,
    FACTOR_MATERIA_SECA

}
